# Generated by Django 5.1.7 on 2025-03-10 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=2)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, null=True)),
                ('dependents', models.IntegerField(default=0)),
                ('pre_existing_conditions', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('education_level', models.CharField(blank=True, choices=[('High School', 'High School'), ('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=12, null=True)),
                ('disabled_mentally', models.BooleanField(default=False)),
                ('disabled_physically', models.BooleanField(default=False)),
                ('insurance_status', models.CharField(blank=True, max_length=50, null=True)),
                ('religious', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('drugs', models.BooleanField(default=False)),
                ('overweight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('date_taken', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.patient')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.testtype')),
            ],
        ),
    ]
