# Generated by Django 3.2.25 on 2025-03-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_patient_testtype_patienttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalousTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('test_type', models.CharField(max_length=255)),
                ('test_value', models.FloatField()),
                ('mean', models.FloatField()),
                ('std_dev', models.FloatField()),
                ('deviation_score', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
